// <auto-generated />
using System;
using ExamBuilderAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamBuilderAI.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430213011_TrueQuestionBank")]
    partial class TrueQuestionBank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamBuilderAI.API.Models.CurriculumUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("GrammarPoints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("int");

                    b.Property<string>("UnitTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Vocabulary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CurriculumUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grade = 8,
                            GrammarPoints = "[\"Gerunds as subjects and objects\", \"Verbs of liking + gerunds\", \"Adverbs of frequency\"]",
                            Topics = "[\"free time activities\", \"hobbies\", \"leisure habits of teenagers\"]",
                            UnitNumber = 1,
                            UnitTitle = "Leisure Activities",
                            Vocabulary = "[\"leisure\", \"hang out\", \"surf the Internet\", \"window shopping\", \"board game\", \"DIY\", \"gardening\", \"crafts\", \"socialise\", \"stroll\"]"
                        },
                        new
                        {
                            Id = 2,
                            Grade = 8,
                            GrammarPoints = "[\"Comparative forms of adjectives\", \"Articles: a/an/the\", \"Simple sentences with adjectives\"]",
                            Topics = "[\"country life vs city life\", \"farming activities\", \"rural landscapes\"]",
                            UnitNumber = 2,
                            UnitTitle = "Life in the Countryside",
                            Vocabulary = "[\"countryside\", \"paddy field\", \"harvest\", \"nomadic\", \"peaceful\", \"vast\", \"pasture\", \"herd\", \"buffalo\", \"rural\"]"
                        },
                        new
                        {
                            Id = 3,
                            Grade = 8,
                            GrammarPoints = "[\"Questions with 'Which/What'\", \"Exclamatory sentences with 'How' and 'What'\", \"Articles with proper nouns\"]",
                            Topics = "[\"ethnic minorities in Vietnam\", \"cultural diversity\", \"traditional customs\"]",
                            UnitNumber = 3,
                            UnitTitle = "Peoples of Viet Nam",
                            Vocabulary = "[\"ethnic group\", \"minority\", \"majority\", \"custom\", \"tradition\", \"costume\", \"festival\", \"stilt house\", \"terraced field\", \"heritage\"]"
                        },
                        new
                        {
                            Id = 4,
                            Grade = 8,
                            GrammarPoints = "[\"Should/Shouldn't for advice\", \"Have to for obligation\", \"Must for strong obligation\"]",
                            Topics = "[\"Vietnamese customs\", \"family traditions\", \"social etiquette\"]",
                            UnitNumber = 4,
                            UnitTitle = "Our Customs and Traditions",
                            Vocabulary = "[\"custom\", \"tradition\", \"praying\", \"worship\", \"respect\", \"ancestor\", \"generation\", \"greeting\", \"polite\", \"palm\"]"
                        },
                        new
                        {
                            Id = 5,
                            Grade = 8,
                            GrammarPoints = "[\"Compound and complex sentences\", \"Adverbial clauses of time\", \"Simple past tense review\"]",
                            Topics = "[\"Vietnamese festivals\", \"cultural celebrations\", \"traditional ceremonies\"]",
                            UnitNumber = 5,
                            UnitTitle = "Festivals in Viet Nam",
                            Vocabulary = "[\"festival\", \"celebration\", \"worship\", \"offering\", \"lantern\", \"performance\", \"float\", \"parade\", \"incense\", \"ritual\"]"
                        },
                        new
                        {
                            Id = 6,
                            Grade = 8,
                            GrammarPoints = "[\"Past continuous tense\", \"Past continuous with 'when' and 'while'\", \"Connectors: First, Then, Next, After that, Finally\"]",
                            Topics = "[\"Vietnamese folk tales\", \"moral lessons\", \"storytelling\"]",
                            UnitNumber = 6,
                            UnitTitle = "Folk Tales",
                            Vocabulary = "[\"folk tale\", \"legend\", \"fairy\", \"knight\", \"giant\", \"cunning\", \"brave\", \"wicked\", \"generous\", \"greed\"]"
                        },
                        new
                        {
                            Id = 7,
                            Grade = 8,
                            GrammarPoints = "[\"Conditional sentences type 1\", \"Conditional sentences type 2\", \"If-clauses\"]",
                            Topics = "[\"types of pollution\", \"causes and effects\", \"environmental solutions\"]",
                            UnitNumber = 7,
                            UnitTitle = "Pollution",
                            Vocabulary = "[\"pollution\", \"contaminate\", \"poison\", \"toxic\", \"dump\", \"sewage\", \"emission\", \"radiation\", \"ecosystem\", \"biodiversity\"]"
                        },
                        new
                        {
                            Id = 8,
                            Grade = 8,
                            GrammarPoints = "[\"Present simple for facts\", \"Passive voice (present simple)\", \"Relative clauses with 'which/that/who'\"]",
                            Topics = "[\"English-speaking countries\", \"cultures around the world\", \"geography and landmarks\"]",
                            UnitNumber = 8,
                            UnitTitle = "English Speaking Countries",
                            Vocabulary = "[\"official language\", \"accent\", \"native speaker\", \"multicultural\", \"diverse\", \"landmark\", \"currency\", \"population\", \"territory\", \"monarchy\"]"
                        },
                        new
                        {
                            Id = 9,
                            Grade = 8,
                            GrammarPoints = "[\"Past perfect tense\", \"Past perfect with 'before/after/when'\", \"Passive voice (past simple)\"]",
                            Topics = "[\"types of natural disasters\", \"disaster preparedness\", \"emergency response\"]",
                            UnitNumber = 9,
                            UnitTitle = "Natural Disasters",
                            Vocabulary = "[\"earthquake\", \"flood\", \"drought\", \"tsunami\", \"tornado\", \"volcanic eruption\", \"typhoon\", \"landslide\", \"evacuate\", \"shelter\"]"
                        },
                        new
                        {
                            Id = 10,
                            Grade = 8,
                            GrammarPoints = "[\"Future continuous tense\", \"Verbs of perception + bare infinitive/present participle\", \"Reported speech (statements)\"]",
                            Topics = "[\"communication methods\", \"body language\", \"online communication etiquette\"]",
                            UnitNumber = 10,
                            UnitTitle = "Communication",
                            Vocabulary = "[\"communicate\", \"body language\", \"gesture\", \"facial expression\", \"verbal\", \"non-verbal\", \"signal\", \"message\", \"netiquette\", \"cyberbullying\"]"
                        },
                        new
                        {
                            Id = 11,
                            Grade = 8,
                            GrammarPoints = "[\"Present perfect tense review\", \"Present perfect with 'for/since/already/yet'\", \"Future simple with 'will' for predictions\"]",
                            Topics = "[\"inventions and technology\", \"future technology\", \"science in daily life\"]",
                            UnitNumber = 11,
                            UnitTitle = "Science and Technology",
                            Vocabulary = "[\"technology\", \"invention\", \"robot\", \"artificial intelligence\", \"device\", \"gadget\", \"software\", \"hardware\", \"innovation\", \"automatic\"]"
                        },
                        new
                        {
                            Id = 12,
                            Grade = 8,
                            GrammarPoints = "[\"May/Might for possibility\", \"Reported speech (questions)\", \"Conditional type 2 review\"]",
                            Topics = "[\"space exploration\", \"life on Mars\", \"the solar system\"]",
                            UnitNumber = 12,
                            UnitTitle = "Life on Other Planets",
                            Vocabulary = "[\"planet\", \"spacecraft\", \"astronaut\", \"galaxy\", \"orbit\", \"gravity\", \"alien\", \"atmosphere\", \"solar system\", \"space station\"]"
                        });
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurriculumUnitId")
                        .HasColumnType("int");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumUnitId");

                    b.HasIndex("GeneratedByUserId");

                    b.HasIndex("SectionId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.ExerciseQuestion", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("ExerciseId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ExerciseQuestions");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.ExerciseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<double>("ScorePercent")
                        .HasColumnType("float");

                    b.Property<int>("TimeTakenSeconds")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<string>("UserAnswers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("ExerciseResults");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.ExerciseSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ExerciseSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "pronunciation",
                            Description = "Choose the word whose underlined part is pronounced differently from the others",
                            DisplayOrder = 1,
                            Icon = "record_voice_over",
                            Name = "Pronunciation"
                        },
                        new
                        {
                            Id = 2,
                            Code = "stress",
                            Description = "Choose the word having a different stress pattern from the others",
                            DisplayOrder = 2,
                            Icon = "graphic_eq",
                            Name = "Stress Pattern"
                        },
                        new
                        {
                            Id = 3,
                            Code = "grammar_vocab",
                            Description = "Choose the correct answer to complete the sentences",
                            DisplayOrder = 3,
                            Icon = "spellcheck",
                            Name = "Grammar & Vocabulary"
                        },
                        new
                        {
                            Id = 4,
                            Code = "synonym",
                            Description = "Choose the word(s) CLOSEST in meaning to the underlined word(s)",
                            DisplayOrder = 4,
                            Icon = "compare_arrows",
                            Name = "Synonym (Closest Meaning)"
                        },
                        new
                        {
                            Id = 5,
                            Code = "antonym",
                            Description = "Choose the word(s) OPPOSITE in meaning to the underlined word(s)",
                            DisplayOrder = 5,
                            Icon = "swap_horiz",
                            Name = "Antonym (Opposite Meaning)"
                        },
                        new
                        {
                            Id = 6,
                            Code = "cloze_test",
                            Description = "Read the passage and choose the correct word for each blank",
                            DisplayOrder = 6,
                            Icon = "article",
                            Name = "Cloze Test"
                        },
                        new
                        {
                            Id = 7,
                            Code = "reading",
                            Description = "Read the passage. Decide True/False and choose the correct answer",
                            DisplayOrder = 7,
                            Icon = "menu_book",
                            Name = "Reading Comprehension"
                        },
                        new
                        {
                            Id = 8,
                            Code = "sentence_completion",
                            Description = "Complete the sentence with the correct words",
                            DisplayOrder = 8,
                            Icon = "edit_note",
                            Name = "Sentence Completion"
                        },
                        new
                        {
                            Id = 9,
                            Code = "word_form",
                            Description = "Use the correct form of the word given in each sentence",
                            DisplayOrder = 9,
                            Icon = "text_rotation_none",
                            Name = "Word Form"
                        },
                        new
                        {
                            Id = 10,
                            Code = "paragraph_writing",
                            Description = "Write a paragraph on the given topic (80-100 words)",
                            DisplayOrder = 10,
                            Icon = "draw",
                            Name = "Paragraph Writing"
                        });
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurriculumUnitId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAssigned")
                        .HasColumnType("bit");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumUnitId");

                    b.HasIndex("SectionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.Exercise", b =>
                {
                    b.HasOne("ExamBuilderAI.API.Models.CurriculumUnit", "CurriculumUnit")
                        .WithMany("Exercises")
                        .HasForeignKey("CurriculumUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExamBuilderAI.API.Models.User", "GeneratedByUser")
                        .WithMany("GeneratedExercises")
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamBuilderAI.API.Models.ExerciseSection", "Section")
                        .WithMany("Exercises")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurriculumUnit");

                    b.Navigation("GeneratedByUser");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.ExerciseQuestion", b =>
                {
                    b.HasOne("ExamBuilderAI.API.Models.Exercise", "Exercise")
                        .WithMany("ExerciseQuestions")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamBuilderAI.API.Models.Question", "Question")
                        .WithMany("ExerciseQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.ExerciseResult", b =>
                {
                    b.HasOne("ExamBuilderAI.API.Models.Exercise", "Exercise")
                        .WithMany("Results")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamBuilderAI.API.Models.User", "User")
                        .WithMany("ExerciseResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.Question", b =>
                {
                    b.HasOne("ExamBuilderAI.API.Models.CurriculumUnit", "CurriculumUnit")
                        .WithMany()
                        .HasForeignKey("CurriculumUnitId");

                    b.HasOne("ExamBuilderAI.API.Models.ExerciseSection", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumUnit");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.CurriculumUnit", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseQuestions");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.ExerciseSection", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.Question", b =>
                {
                    b.Navigation("ExerciseQuestions");
                });

            modelBuilder.Entity("ExamBuilderAI.API.Models.User", b =>
                {
                    b.Navigation("ExerciseResults");

                    b.Navigation("GeneratedExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
